export const fullStackPortfolioEnglish = [
  {
    id: 1,
    title: "Malvarosa page",
    img: "assets/Malvarosa.png",
    link: "https://malvarosa.netlify.app/",
    text: "This is my final React project in CoderHouse. It consists of a flower e-commerce developed with React.js, Material UI, Styled Component, among others. I used an API called Commerce.JS that does Backend work, specifically for e-commerce.",
    github: "https://github.com/DanielRamosValenzuela/Malvarosa",
  },
  {
    id: 2,
    title: "Delivex page",
    img: "assets/delivex.png",
    link: "https://delivex.000webhostapp.com/index.html",
    subLink:
      "https://www.figma.com/file/I7YHxuR1RTr56mumPvHqio/Deliexp?node-id=3%3A2",
    text: `This project only uses HTML and CSS, with a bit of JavaScript and jQUery, I did it for my HTML and CSS course at CoderHouse. I used what I knew about UI/UX which is not much, but the idea was to learn. I made a sketch in Figma where you can see it in the following link:`,
    github: "https://github.com/DanielRamosValenzuela/delivexpage",
  },
  {
    id: 9,
    title: "Portfolio page",
    img: "assets/portfoliopage.png",
    link: "https://delivex.000webhostapp.com/index.html",
    text: `This portfolio was made in React and SASS.`,
    github: "https://github.com/DanielRamosValenzuela/portfoliodr",
  },
  {
    id: 10,
    title: "Papinos page",
    img: "assets/papinospage.png",
    link: "http://209.126.8.246:8080/papino.com",
    text: `This is my JavaScript project at CoderHouse, it is written in Vanilla JavaScript with Node. JS and SQL Server database, I disabled the create user since the dont have email verification. Although, if you create an account it will save it in the local storage, you can enter and test the application with my username: daniel.andres.ramos.v@gmail.com, password: 123456 (Changing password is disabled), you can also use the complete aplication without a user. This project was on the top 10.`,
    github: "https://github.com/DanielRamosValenzuela/LosPapinosPage",
  },
  {
    id: 11,
    title: "Indicators",
    img: "assets/indicadores.png",
    link: "https://indicadoresbanco.netlify.app/",
    text: `This is a task to apply for companies, it consists of a call to an API that they gave me to show economic indicators. Bootstrap had to be used for the design.`,
    github: "https://github.com/DanielRamosValenzuela/indicadores",
  },
];

export const cursosPortfolioEnglish = [
  {
    id: 3,
    title: "HTML and CSS CoderHouse",
    img: "assets/certificadoHTML.png",
    link: "https://www.coderhouse.cl/certificados/6132179d0153de0010b26964",
    text: "HTML and CSS Certificate in CouderHouse",
    github: "",
  },
  {
    id: 4,
    title: "JavaScript CoderHouse",
    img: "assets/certificadoJS.png",
    link: "https://www.coderhouse.cl/certificados/61465148cd5a33004f86c3e5",
    text: "JavaScript Certificate in CouderHouse",
    github: "",
  },
  {
    id: 5,
    title: "React CoderHouse",
    img: "assets/reactcoder.png",
    link: "https://www.coderhouse.cl/certificados/6189efe8ec61e30036034268",
    text: "React Certificate in CouderHouse",
    github: "",
  },
  {
    id: 6,
    title: "JavaScript Udemy",
    img: "assets/udemyJS.jpg",
    link: "https://udemy-certificate.s3.amazonaws.com/pdf/UC-dec87b81-c9c1-4027-a7c5-ee6f6071f06d.pdf",
    text: "Udemy Certificate from my course from: The Complete JavaScript Course 2021: From Zero to Expert!",
    github: "",
  },
  {
    id: 7,
    title: "JavaScript Understanding",
    img: "assets/udemyJS2.jpg",
    link: "https://udemy-certificate.s3.amazonaws.com/pdf/UC-113bd549-ce20-4449-982b-0219d23df588.pdf",
    text: "Udemy Certificate from my course from: JavaScript, Understanding the Weird Part",
    github: "",
  },
  {
    id: 8,
    title: "REACT Udemy",
    img: "assets/udemyREACT.jpg",
    link: "https://udemy-certificate.s3.amazonaws.com/pdf/UC-4a052050-bddd-4e05-9b56-4319a8550766.pdf",
    text: "Udemy Certificate from my course from: REACT: from zero to expert (Hooks and MERN)",
    github: "",
  },
];
