export const fullStackPortfolio = [
  {
    id: 1,
    title: "Malvarosa page",
    img: "assets/Malvarosa.png",
    link: "https://malvarosa.netlify.app/",
    text: "Este trabajo lo hice para mi proyecto final de React en CoderHouse, consiste en un e-commerce de flores escrito con React.js, Material UI, Styled Component, entre otros. Utilice una API llamada Commerce.JS que hace el trabajo de Backend y específicamente para e-commerce.",
    github: "https://github.com/DanielRamosValenzuela/Malvarosa",
  },
  {
    id: 2,
    title: "Delivex page",
    img: "assets/delivex.png",
    link: "https://delivex.000webhostapp.com/index.html",
    subLink:
      "https://www.figma.com/file/I7YHxuR1RTr56mumPvHqio/Deliexp?node-id=3%3A2",
    text: `Este proyecto solo utilice HTML y CSS, con un poco de JavaScript y jQUery, lo hice para mi ramo de HTML y CSS en Coder House, intente guiarme por lo que sabía de UI/UX que no es mucho, pero la idea era aprender. Hice un sketch en Figma en donde lo puede visualizar en el siguiente link:`,
    github: "https://github.com/DanielRamosValenzuela/delivexpage",
  },
  {
    id: 9,
    title: "Portfolio page",
    img: "assets/portfoliopage.png",
    link: "https://delivex.000webhostapp.com/index.html",
    text: "Este mismo portfolio esta hecho en React y SASS.",
    github: "https://github.com/DanielRamosValenzuela/portfoliodr",
  },
  {
    id: 10,
    title: "Papinos page",
    img: "assets/papinospage.png",
    link: "http://209.126.8.246:8080/papino.com",
    text: `Este trabajo lo utilice para mi proyecto de JavaScript en Coder House, está escrito en Vanilla JavaScript con Node.JS y base de datos SQL Server, tuve que deshabilitar el crear usuario ya que no hice verificación por mail, aunque si te creas una cuenta lo guardara en el local storage, puedes entrar y probar la aplicación con mi usuario: daniel.andres.ramos.v@gmail.com, password:123456 (También deshabilite el cambiar password), si no también puedes usar la aplicación sin usuario, cumple la misma finalidad, en este proyecto logre sacar el top 10 del curso.`,
    github: "https://github.com/DanielRamosValenzuela/LosPapinosPage",
  },
  {
    id: 11,
    title: "Indicadores",
    img: "assets/indicadores.png",
    link: "https://indicadoresbanco.netlify.app/",
    text: `Este es un trabajo que realice para postular a empresas, consiste en una llamada a una API que me dieron para mostrar indicadores económicos. Se tenía que usar Bootstrap para el diseño.`,
    github: "https://github.com/DanielRamosValenzuela/indicadores",
  },
];

export const cursosPortfolio = [
  {
    id: 3,
    title: "HTML y CSS CoderHouse",
    img: "assets/certificadoHTML.png",
    link: "https://www.coderhouse.cl/certificados/6132179d0153de0010b26964",
    text: "Certificado de HTML y CSS en CoderHouse",
    github: "",
  },
  {
    id: 4,
    title: "JavaScript CoderHouse",
    img: "assets/certificadoJS.png",
    link: "https://www.coderhouse.cl/certificados/61465148cd5a33004f86c3e5",
    text: "Certificado de JavaScript en CoderHouse",
    github: "",
  },
  {
    id: 5,
    title: "React CoderHouse",
    img: "assets/reactcoder.png",
    link: "https://www.coderhouse.cl/certificados/6189efe8ec61e30036034268",
    text: "Certificado de React en CoderHouse",
    github: "",
  },
  {
    id: 6,
    title: "JavaScript Udemy",
    img: "assets/udemyJS.jpg",
    link: "https://udemy-certificate.s3.amazonaws.com/pdf/UC-dec87b81-c9c1-4027-a7c5-ee6f6071f06d.pdf",
    text: "Certificado de Udemy de mi curso de: The Complete JavaScript Course 2021: From Zero to Expert!",
    github: "",
  },
  {
    id: 7,
    title: "JavaScript Understanding",
    img: "assets/udemyJS2.jpg",
    link: "https://udemy-certificate.s3.amazonaws.com/pdf/UC-113bd549-ce20-4449-982b-0219d23df588.pdf",
    text: "Certificado de Udemy de mi curso de JavaScript, Understanding the Weird Part",
    github: "",
  },
  {
    id: 8,
    title: "REACT Udemy",
    img: "assets/udemyREACT.jpg",
    link: "https://udemy-certificate.s3.amazonaws.com/pdf/UC-4a052050-bddd-4e05-9b56-4319a8550766.pdf",
    text: "Certificado de Udemy de mi curso de REACT: De cero a experto (Hooks y MERN)",
    github: "",
  },
];
